version: 2

models:
  - name: stg_crm_accounts
    description: "Deduplicated CRM accounts with normalized text fields."
    columns:
      - name: crm_account_id
        tests: [not_null, unique]
      - name: lifecycle_stage
        tests:
          - accepted_values:
              arguments:
                values: ["lead","mql","sql","opportunity","customer","churned"]

  - name: stg_crm_contacts
    description: "CRM contacts with normalized email and derived email_domain."
    columns:
      - name: crm_contact_id
        tests: [not_null, unique]
      - name: crm_account_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_crm_accounts')
                field: crm_account_id
      - name: email
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "email like '%@%'"
